Add edit functionality for notes
ronin-rb/ronin-app pull request #101
Opened 2024-04-21 19:14 UTC by AI-Mozi

#58

2024-04-21 19:16 UTC, AI-Mozi commented
@postmodern take a look at it please and let me know if you like it or what would you change. Code is not fully completed, I'll have to "refactor" it a bit later.

2024-04-22 00:24 UTC, postmodern requested changes
Needs HTML escaping in the views, especially on `note.body`; or we should render `note.body` as markdown. Also should add `hattr` to all emitted attributes in the views, "just to be safe". I'm strongly against pulling in any external JavaScript assets, especially fonts, and prefer we just use the user's browser's default font.

2024-04-22 00:24 UTC, postmodern commented on views/_notes.erb
> +                  <textarea id="note-edit-textarea-<%= note.id %>" class="textarea" name="body" placeholder="Edit a note..."><%= note.body %></textarea>
Needs `h` HTML escaping, or we need to render the note body as markdown and inline the primitive HTML.

2024-04-22 00:24 UTC, postmodern commented on views/_notes.erb
> +                  <button class="update-note button is-small is-primary" data-note-id=<%= note.id %> data-note-body=<%= note.body %>>Save</button>
Attributes need `hattr` escaping.

2024-04-22 00:24 UTC, postmodern commented on views/_notes.erb
> +          <div id="note-edit-body-<%= note.id %>" class="mb-0 p-4"><%= note.body %></div>
Needs `h` HTML escaping on `note.body`, or we should render it as markdown.

2024-04-22 00:24 UTC, postmodern commented on views/_notes.erb
> +          <small class="is-size-7">Created at: <%= note.created_at %></small>
Probably safe, but I'd escape the timestamp using `h` just to be safe.

2024-04-22 00:24 UTC, postmodern commented on views/_notes.erb
> +                <a class="dropdown-item py-2 delete-note has-text-danger" data-note-id=<%= note.id %>>Delete</a>
Probably a good idea to escape `note.id` with `hattr` just to be safe, and that it doesn't trigger false positives on some security scan.

2024-04-22 00:24 UTC, postmodern commented on views/_notes.erb
> +                <a class="dropdown-item py-2 edit-note" data-note-id=<%= note.id %>>Edit</a>
Probably a good idea to escape `note.id` with `hattr` just to be safe, and that it doesn't trigger false positives on some security scan.

2024-04-22 00:24 UTC, postmodern commented on views/_notes.erb
> +          <div id="note-edit-body-<%= note.id %>" class="mb-0 p-4"><%= note.body %></div>
Probably a good idea to escape `note.id` with `hattr` just to be safe, and that it doesn't trigger false positives on some security scan.

2024-04-22 00:24 UTC, postmodern commented on views/_notes.erb
> +          <div id="note-edit-form-<%= note.id %>" style="display: none">
Probably a good idea to escape `note.id` with `hattr` just to be safe, and that it doesn't trigger false positives on some security scan.

2024-04-22 00:24 UTC, postmodern commented on views/_notes.erb
> +                  <textarea id="note-edit-textarea-<%= note.id %>" class="textarea" name="body" placeholder="Edit a note..."><%= note.body %></textarea>
Probably a good idea to escape `note.id` with `hattr` just to be safe, and that it doesn't trigger false positives on some security scan.

2024-04-22 00:24 UTC, postmodern commented on views/layout.erb
> +    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
Let's not add a font just yet and use the browser's default font, especially not some external JavaScript asset font. The whole app should be able to load and run without an internet connection.

2024-04-22 00:24 UTC, postmodern commented on app/db.rb
> +    unless @record || @record.update(params)
I would return a different error code if the `update` fails, like `400` (Bad Request).

2024-04-22 00:25 UTC, postmodern commented
Noticed that `noteId` is used a lot in multiple `id` elements. I wonder if we could use `data` attributes for that? Or have one query to find the outer most `div` with the `noteId`, and then sub-select the specific elements within the div based on `class` or element type.

2024-04-22 00:33 UTC, postmodern commented on views/layout.erb
> +    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
Oooh this is for the icons. For SVG icons just download the desired icon files and put them into `public/images/`. Previously I would just do a Google Images search for "SVG edit icon" and filter by Creative Commons. I recently discovered [iconduck.com](https://iconduck.com/search?query=edit+icon) which is a Free and Open Source collection of icons, and offers SVG downloads. We should probably just use individual icons from them.

2024-04-22 06:11 UTC, postmodern commented
Doing a visual inspection, I think the grey text on black background for the comment header is hard to see in bright-mode. I'd use white text on a black background, or at least a brighter shade of grey.
![localhost_1337_db_host_names_1 (1)](https://github.com/ronin-rb/ronin-app/assets/12671/b2261c45-67cf-4315-b812-e1f04ed8523e)

2024-04-22 06:13 UTC, postmodern commented
It also appears that the Delete doesn't remove the comment `div` immediately. Edit works perfectly thought.

2025-02-16 20:30 UTC, postmodern commented
Could you rebase this against the `0.2.0` branch? I'm having trouble testing this locally.

2025-02-18 19:46 UTC, closed without merging

2025-02-18 19:50 UTC, moozzi commented
Ohh.. I didn't wanto to do it...
@postmodern do you have a copy of the code locally? 😅