Add route for inspecting sidekiq jobs
ronin-rb/ronin-app pull request #63
Opened 2023-11-06 14:51 UTC by AI-Mozi

#8

2023-11-07 00:31 UTC, postmodern requested changes
Minor style changes.

2023-11-07 00:31 UTC, postmodern commented on app.rb
> +        run_at: Time.at(worker["run_at"])
Vertically align the values of the Hash.

2023-11-07 00:31 UTC, postmodern commented on app.rb
> +      {
Add a newline between 774 and 775.

2023-11-07 00:31 UTC, postmodern commented on config/sidekiq.rb
> +require 'sidekiq/api'
Move this require into `app.rb`, since that's the only play we use the `Sidekiq::API`.

2023-11-07 00:33 UTC, postmodern commented
This is awesome. I'll open separate tickets for some other ideas, like listing currently running jobs at the top, or adding a JavaScript async refresh.

2023-11-07 07:50 UTC, AI-Mozi commented
Current design of this view may not be the best you've ever seen, but imo is enough for now.
I've also found out that our dark mode style needs some changes to work well with bulma styles (for example `box` class looks much better on light mode).

2023-11-08 11:11 UTC, postmodern requested changes
Noticed a few things about block variable names and using `<b>` instead of `<strong>`.

2023-11-08 11:11 UTC, postmodern commented on views/queue.erb
> +        <p><b>arguments:</b>
Use `<strong>` or `<h5>`/`<h6>`.

2023-11-08 11:11 UTC, postmodern commented on views/queue.erb
> +            <% arg.each do |k, v| %>
Use `key` and `value`. I'm not a fan of single letter variable names.

2023-11-08 11:11 UTC, postmodern commented on views/queue.erb
> +              <%= k %>: <%= v %>
Wrap the key name in `<strong>`.

2023-11-08 11:11 UTC, postmodern commented on views/queue.erb
> +              <%= k %>: <%= v %>
Maybe wrap the value in `<kbd>`?

2023-11-08 11:11 UTC, postmodern commented on views/queue.erb
> +          <div class="column is-one-third py-0"><b>Run at:</b> <%= worker[:run_at] %></div>
Use `<strong>` instead of `<b>`.

2023-11-08 11:11 UTC, postmodern commented on views/queue.erb
> +        <p class="mb-0"><b>queue:</b> <%= worker[:queue] %></p>
Use `<strong>` or `<h3>`.

2023-11-08 11:11 UTC, postmodern commented on app.rb
> +    @workers = Sidekiq::Workers.new.map do |_p, _t, worker|
Use `_process_id` and `_thread_id` so it's obvious what those arguments are for, even though we currently are not using them.

2023-11-08 14:06 UTC, postmodern approved these changes

2023-11-08 14:07 UTC, merged