Add views and routes for Organization model
ronin-rb/ronin-app pull request #83
Opened 2023-12-20 17:36 UTC by AI-Mozi

#78 #79

2023-12-20 17:38 UTC, AI-Mozi commented
@postmodern Could you pleas check if `show` view works correctly for you? (I had some problems locally).
I'm also not sure if I've added all necessary fields.

2023-12-20 23:00 UTC, postmodern commented
@AI-Mozi fixed an issue in `ronin-db-activerecord` and had to recreate my database. Probably should change `./scripts/server` to use a local database in `db/` to make development easier?

Here is what a new `Organization` with just a name looks like:
![localhost_1337_db_organizations_1](https://github.com/ronin-rb/ronin-app/assets/12671/5db1cff2-c4e4-4068-81e5-e127cac024d5)

2023-12-20 23:06 UTC, postmodern requested changes
Some suggestions on the links/routes to other models associated with `Organization`.

2023-12-20 23:06 UTC, postmodern commented on views/db/organizations/show.erb
> +          <p><a href="/db/departments/<%=h department.id %>"><%=h department %></a></p>
Should be named `/db/organization_departments/:id` (if we want to link directly to departments, without knowing their parent org ID) or `/db/organizations/:id/departments/:dept_id`.

2023-12-20 23:06 UTC, postmodern commented on views/db/organizations/show.erb
> +          <p><a href="/db/members/<%=h member.id %>"><%=h member %></a></p>
Same here, should be either `/db/organization_members/:id` or `/db/organizations/:id/members/:member_id`.

2023-12-20 23:06 UTC, postmodern commented on views/db/organizations/show.erb
> +          <p><a href="/db/customers/<%=h customer.id %>"><%=h customer %></a></p>
`Organization#customers` returns `Array<Person>`, so we could link directly to `/db/people/:id`.

2023-12-20 23:06 UTC, postmodern commented on views/db/organizations/show.erb
> +          <p><a href="/db/vendors/<%=h vendor.id %>"><%=h vendor %></a></p>
`Organization#vendors` returns `Array<Organization>`, so we could link directly to `/db/organizations/:id`.

2023-12-20 23:06 UTC, postmodern commented on views/db/organizations/show.erb
> +
Extra newline.

2023-12-21 08:40 UTC, postmodern approved these changes

2023-12-21 08:41 UTC, merged